name: 'Run All Tests'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/deck_of_cards_api.postman_collection.json
          reporters: cli
          iterationCount: 4
          iterationData: deck_data.csv